export const promotions = [
    {
        id: 9,
        source: 'Livelo',
        dest: 'Latam',
        bonus: 35,
        participants: ['Livelo'],
        startDate: '2025-03-24',
        endDate: '2025-03-24',
        rules: ['id: 9,',
            '35% de bônus – assinantes do Clube Latam ou do Clube Livelo.',
            '20% de bônus – demais clientes.',
            'Transferência mínima de 15.000 pontos para o Latam.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/67ddc4f51a3ab_regulamento-livelo-milhas-extras-2025-03.pdf?utm_source=passageiro_de_primeira&utm_medium=site" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 10,
        source: 'Itaú',
        dest: 'Latam',
        bonus: 40,
        participants: ['Itaú', 'Credicard'],
        startDate: '2025-04-05',
        endDate: '2025-04-05',
        rules: ['id: 10,',
            '40% de milhas extras: assinantes do Clube Latam;',
            '20% de milhas extras: não assinantes do Clube.',
            'Regulamento completo da campanha <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/67ebd84ad7cd5_regulamento-Itaú-abril-25-docx.pdf" target="_blank">Itaú</a> e <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/67ebd85ed768c_regulamento-credicard-abril-25-docx.pdf" target="_blank">Credicard</a>.'
        ]
    },
    {
        id: 11,
        source: 'Sisprime',
        dest: 'Latam',
        bonus: 40,
        participants: ['Sisprime'],
        startDate: '2025-04-25',
        endDate: '2025-04-25',
        rules: ['id: 11,',
            '40% de milhas extras: assinantes do Clube Latam;',
            '20% de milhas extras: não assinantes do Clube.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/6807f8b4b6c59_regulamento-sisprime-milhas-extras-abril-de-2025-docx-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 12,
        source: 'Bancos',
        dest: 'Latam',
        bonus: 40,
        participants: ['Itaú', 'Credicard', 'SICREDI', 'Banco Banrisul', 'SICOOB/Coopera', 'Unicred', 'Banco Banestes', 'Banco Pan', 'Banco do Nordeste', 'Banco Mercantil', 'Bourbon Cartões', 'Banpará', 'Banco BV', 'Banco Industrial BIB', 'Sisprime'],
        startDate: '2025-04-29',
        endDate: '2025-04-29',
        rules: ['id: 12,',
            '40% de milhas extras: assinantes do Clube Latam;',
            '20% de milhas extras: não assinantes do Clube.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/67fed421e2e25_bancos-institucional-pontos-extras-2025-04-docx-1.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 13,
        source: 'Livelo',
        dest: 'Latam',
        bonus: 35,
        participants: ['Livelo'],
        startDate: '2025-05-13',
        endDate: '2025-05-14',
        rules: ['id: 13,',
            '35% de bônus – assinantes do Clube Latam ou do Clube Livelo;',
            '20% de milhas extras: não assinantes do Clube.',
            'Transferência mínima de 15.000 pontos para o Latam.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/682242394aaaf_regulamento-livelo-pontos-extras-2025-05-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 14,
        source: 'Caixa',
        dest: 'Latam',
        bonus: 35,
        participants: ['Caixa'],
        startDate: '2025-06-23',
        endDate: '2025-05-25',
        rules: ['id: 14,',
            '30% de bônus – para assinantes do Clube Latam.',
            '20% de bônus – para demais clientes Latam.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/68594b5a1883b_regulamento-caixa-junho-25-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 15,
        source: 'Bancos',
        dest: 'Latam',
        bonus: 30,
        participants: ['Itaú', 'Credicard', 'Cartões Caixa', 'SICREDI', 'Banco Banrisul', 'SICOOB / Coopera', 'Unicred', 'Banco Banestes', 'Banco Pan', 'Banco do Nordeste', 'Banco Mercantil', 'Bourbon Cartões', 'Banpará', 'Banco BV', 'Banco Industrial BIB', 'Sisprime'],
        startDate: '2025-07-07',
        endDate: '2025-07-08',
        rules: ['id: 15,',
            '30% de bônus – assinantes do Clube Latam;',
            '20% de bônus – demais clientes.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/685d7458eb17f_bancos-institucional-pontos-extras-2025-07-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 16,
        source: 'Bancos',
        dest: 'Latam',
        bonus: 35,
        participants: ['Livelo', 'Itaú', 'Credicard', 'Cartões Caixa', 'Banco Banrisul', 'SICREDI', 'Unicred', 'Banco Banestes', 'SICOOB / Coopera', 'Banco do Nordeste', 'Banco Mercantil', 'Bourbon Cartões', 'Banpará', 'Banco BV', 'Banco Industrial BIB', 'Sisprime'],
        startDate: '2025-08-18',
        endDate: '2025-08-21',
        rules: ['id: 16,',
            '35% de bônus – assinantes do Clube Latam.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/689cee57c86cb_bancos-institucional-milhas-extras-2025-08-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 17,
        source: 'BTG',
        dest: 'Latam',
        bonus: 30,
        participants: ['BTG'],
        startDate: '2025-09-08',
        endDate: '2025-09-12',
        rules: ['id: 17,',
            '30% de bônus – para todas as transferências.',
            'Para mais informações, confira o <a href="https://passageirodeprimeira.com/wp-content/uploads/2025/09/latam-pass-oferece-ate-30-de-bonus-nas-transferencias-de-pontos-do-btg-68b5c879cede5-regulamento-btg-milhas-extras-set-2025-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 18,
        source: 'Esfera',
        dest: 'Latam',
        bonus: 30,
        participants: ['Esfera'],
        startDate: '2025-09-29',
        endDate: '2025-09-30',
        rules: ['id: 18,',
            '30% de bônus – para todas as transferências.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/68d5af11b1104_regulamento-esfera-set-25-docx.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 19,
        source: 'Baneste',
        dest: 'Latam',
        bonus: 30,
        participants: ['Baneste'],
        startDate: '2025-10-22',
        endDate: '2025-10-24',
        rules: ['id: 19,',
            '30% de bônus – para todas as transferências.',
            'Para mais informações, confira o <a href="https://d3rwujusajfqlr.cloudfront.net/uploads/68f66b4862e78_regulamento-banestes-milhas-extras-outubro-de-2025-docx-2.pdf" target="_blank">regulamento oficial.</a>'
        ]
    },
    {
        id: 20,
        source: 'Nubank',
        dest: 'Latam',
        bonus: 30,
        participants: ['Esfera'],
        startDate: '2025-11-24',
        endDate: '2025-11-25',
        rules: ['id: 20,',
            '30% de bônus – para todas as transferências.'
        ]
    },
    {
        id: 21,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-01-16',
        endDate: '2025-01-17',
        rules: ['id: 21,',
            '80% de bônus (70% + 10% de bônus do Plano) – Plano 20.000 ou Categoria Diamante',
            '78% de bônus (70% + 8% de bônus do Plano) – Plano 10.000',
            '77% de bônus (70% + 7% de bônus do Plano) – Plano 7.000',
            '75% de bônus (70% + 5% de bônus do Plano) – Plano 5.000',
            '73% de bônus (70% + 3% de bônus do Plano) – Plano 2.000 e Plano 3.000',
            '70% de bônus  – Plano 1.000',
            '10% de bônus extra ao resgatar um voo'
        ]
    },
    {
        id: 22,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 90,
        participants: ['Todos os bancos'],
        startDate: '2025-01-28',
        endDate: '2025-01-29',
        rules: ['id: 22,',
            '90% de bônus (80% + 10% de bônus do Plano) – Plano 20.000 ou Categoria Diamante',
            '88% de bônus (80% + 8% de bônus do Plano) – Plano 10.000',
            '87% de bônus (80% + 7% de bônus do Plano) – Plano 7.000',
            '85% de bônus (80% + 5% de bônus do Plano) – Plano 5.000',
            '83% de bônus (80% + 3% de bônus do Plano) – Plano 2.000 e Plano 3.000',
            '80% de bônus – Plano 1.000',
            '60% de bônus – Clientes da categoria Ouro',
            '50% de bônus – Clientes da categoria Prata',
            '40% de bônus – demais clientes'
        ]
    },
    {
        id: 23,
        source: 'Esfera',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Esfera'],
        startDate: '2025-02-10',
        endDate: '2025-02-11',
        rules: ['id: 23,',
            '80% de bônus: Assinantes do Clube Esfera que assinem o Clube Smiles ou com status Diamante',
            '70% de bônus: Assinantes do Clube Esfera, Clube Smiles, e/ou status Diamante.',
            '50% de bônus – demais clientes'
        ]
    },
    {
        id: 24,
        source: 'BB Estilo',
        dest: 'Smiles',
        bonus: 70,
        participants: ['BB Estilo'],
        startDate: '2025-04-22',
        endDate: '2025-04-24',
        rules: ['id: 24,',
            '70% de bônus – Para assinantes do Clube Smiles e/ou categoria Diamante',
            '40% de bônus – Demais clientes'
        ]
    },
    {
        id: 25,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 90,
        participants: ['Todos os bancos'],
        startDate: '2025-05-26',
        endDate: '2025-05-28',
        rules: ['id: 25,',
            '90% de bônus – Assinantes do Clube Smiles no plano 20.000 ou Categoria Diamante',
            '88% de bônus – Assinantes do Clube Smiles no plano 10.000',
            '87% de bônus – Assinantes do Clube Smiles no plano 7.000',
            '85% de bônus – Assinantes do Clube Smiles no plano 5.000',
            '83% de bônus – Assinantes do Clube Smiles no plano 2.000 e 3.000',
            '80% de bônus – Assinantes do Clube Smiles no plano 1.000',
            '50% de bônus – Demais clientes.'
        ]
    },
    {
        id: 26,
        source: 'Livelo',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Livelo'],
        startDate: '2025-06-09',
        endDate: '2025-06-10',
        rules: ['id: 26,',
            '80% de bônus: assinantes do Clube Livelo e Clube Smiles e/ou clientes Diamante;',
            '70% de bônus: assinantes Clube Livelo ou Clube Smiles e/ou categoria Diamante;',
            '50% de bônus: demais clientes.'
        ]
    },
    {
        id: 27,
        source: 'BTG Pactual',
        dest: 'Smiles',
        bonus: 90,
        participants: ['BTG Pactual'],
        startDate: '2025-07-08',
        endDate: '2025-07-10',
        rules: ['id: 27,',
            '90% de bônus – Assinantes do Clube Smiles de todos os planos ou Categoria Diamante;',
            '50% de bônus – Demais clientes Smiles.'
        ]
    },
    {
        id: 28,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-07-10',
        endDate: '2025-07-13',
        rules: ['id: 28,',
            '80% de bônus – Assinantes do Clube Smiles no plano 20.000 ou Categoria Diamante',
            '78% de bônus – Assinantes do Clube Smiles no plano 10.000',
            '77% de bônus – Assinantes do Clube Smiles no plano 7.000',
            '75% de bônus – Assinantes do Clube Smiles no plano 5.000',
            '73% de bônus – Assinantes do Clube Smiles no plano 2.000 e 3.000',
            '70% de bônus – Assinantes do Clube Smiles no plano 1.000',
            '40% de bônus – Demais clientes.'
        ]
    },
    {
        id: 29,
        source: 'Esfera',
        dest: 'Smiles',
        bonus: 90,
        participants: ['Esfera'],
        startDate: '2025-09-15',
        endDate: '2025-09-16',
        rules: ['id: 29,',
            '90% de bônus – Assinantes do Clube Smiles no plano 20.000 ou Categoria Diamante',
            '88% de bônus – Assinantes Clube 10.000',
            '87% de bônus – Assinantes Clube 7.000',
            '85% de bônus – Assinantes Clube 5.000',
            '83% de bônus – Assinantes Clube 2.000 e 3.000',
            '80% de bônus – Assinantes Clube 1.000',
            '50% de bônus – Demais clientes.'
        ]
    },
    {
        id: 30,
        source: 'Livelo',
        dest: 'Smiles',
        bonus: 90,
        participants: ['Livelo'],
        startDate: '2025-11-24',
        endDate: '2025-11-25',
        rules: ['id: 30,',
            '90% de bônus – Assinantes do Clube Smiles e/ou Diamante e/ou Clube Livelo',
            '50% de bônus – Demais clientes.'
        ]
    },
    {
        id: 31,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 100,
        participants: ['Todos os bancos'],
        startDate: '2025-11-27',
        endDate: '2025-11-27',
        rules: ['id: 31,',
            '100% de bônus – Assinantes do Clube Smiles no plano 20.000 ou Categoria Diamante',
            '98% de bônus – Assinantes Clube 10.000',
            '97% de bônus – Assinantes Clube 7.000',
            '95% de bônus – Assinantes Clube 5.000',
            '93% de bônus – Assinantes Clube 2.000 e 3.000',
            '90% de bônus – Assinantes Clube 1.000.'
        ]
    },
    {
        id: 32,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-12-11',
        endDate: '2025-12-12',
        rules: ['id: 32,',
            '80% de bônus – Assinantes do Clube Smiles no plano 20.000 ou Categoria Diamante',
            '78% de bônus – Assinantes Clube 10.000',
            '77% de bônus – Assinantes Clube 7.000',
            '75% de bônus – Assinantes Clube 5.000',
            '73% de bônus – Assinantes Clube 2.000 e 3.000',
            '70% de bônus – Assinantes Clube 1.000.'
        ]
    },
    {
        id: 33,
        source: 'Caixa',
        dest: 'Azul',
        bonus: 164,
        participants: ['Caixa'],
        startDate: '2025-01-12',
        endDate: '2025-01-12',
        rules: ['id: 33,',
            '164% de bônus – assinantes do Clube Azul do plano 20.000 ou clientes Diamante',
            '90% de bônus – assinantes do Clube Azul dos planos 1.000, 2.000, 3.000, 5.000 e 10.000',
            '50% de bônus – demais clientes Azul.'
        ]
    },
    {
        id: 34,
        source: 'Itaú',
        dest: 'Azul',
        bonus: 100,
        participants: ['Itaú'],
        startDate: '2025-01-20',
        endDate: '2025-01-23',
        rules: ['id: 34,',
            '80% de bônus – todos os clientes Azul',
            '100% de bônus – assinantes Clube Azul.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 35,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-03-10',
        endDate: '2025-03-12',
        rules: ['id: 35,',
            '80% de bônus: Cliente Diamante e/ou Assinantes do Clube Azul 20.000',
            '70% de bônus: Assinantes do Clube Azul 1.000, 2.000, 5.000 e 10.000',
            '40% de bônus: Não assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 36,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 105,
        participants: ['Todos os bancos'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 36,',
            '105% de bônus – todos os clientes Azul Fidelidade',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 37,
        source: 'Livelo',
        dest: 'Azul',
        bonus: 100,
        participants: ['Livelo'],
        startDate: '2025-06-16',
        endDate: '2025-06-18',
        rules: ['id: 37,',
            '100% de bônus: assinantes do Clube Azul e/ou Clube Livelo, com conta ativa',
            '50% de bônus: demais clientes.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses e menos de 12 meses de assinatura',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 38,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 70,
        participants: ['Todos os bancos'],
        startDate: '2025-07-07',
        endDate: '2025-07-09',
        rules: ['id: 38,',
            '70% de bônus: Assinante do Clube Azul',
            '50% de bônus: Clientes Azul.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 39,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 96,
        participants: ['Todos os bancos'],
        startDate: '2025-08-11',
        endDate: '2025-08-17',
        rules: ['id: 39,',
            '96% de bônus: Assinante do Clube Azul',
            '70% de bônus: Clientes Azul.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 40,
        source: 'Caixa',
        dest: 'Azul',
        bonus: 90,
        participants: ['Caixa'],
        startDate: '2025-09-08',
        endDate: '2025-09-17',
        rules: ['id: 40,',
            'Clientes Clube Azul: 90% de bônus',
            'Demais clientes: 50% de bônus.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 41,
        source: 'Esfera',
        dest: 'Azul',
        bonus: 80,
        participants: ['Esfera'],
        startDate: '2025-09-25',
        endDate: '2025-09-27',
        rules: ['id: 41,',
            '60% de bônus – clientes Azul Fidelidade',
            '80% de bônus – assinantes Clube Azul',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 42,
        source: 'Livelo',
        dest: 'Azul',
        bonus: 95,
        participants: ['Livelo'],
        startDate: '2025-11-03',
        endDate: '2025-11-05',
        rules: ['id: 42,',
            '95% de bônus: assinantes do Clube Azul e/ou Clube Livelo, com conta ativa',
            '75% de bônus: demais clientes.',
            '+ 5% de bônus – assinantes Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes Clube Azul planos 1.000, 2.000, 3.000 e 5.000 há mais de 1 ano',
            '+ 20% de bônus – assinantes Clube Azul planos 10.000 e 20.000 há mais de 1 ano.'
        ]
    },
    {
        id: 43,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 100,
        participants: ['Todos os bancos'],
        startDate: '2025-11-17',
        endDate: '2025-11-19',
        rules: ['id: 43,',
            'Clientes Azul: 80% de bônus',
            'Assinantes Clube Azul: 100% de bônus',
            '+ 5% de bônus – assinantes do Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes do Clube Azul entre 1 a 2 anos (12 a 35 meses)',
            '+ 20% de bônus – assinantes do Clube Azul entre 3 e 4 anos (36 a 59 meses)',
            '+ 30% de bônus – assinantes do Clube Azul há mais de 5 anos (60 meses)'
        ]
    },
    {
        id: 44,
        source: 'Livelo',
        dest: 'Azul',
        bonus: 100,
        participants: ['Livelo'],
        startDate: '2025-11-18',
        endDate: '2025-11-19',
        rules: ['id: 44,',
            'Clientes Azul: 80% de bônus',
            'Assinantes Clube Azul: 100% de bônus',
            '+ 5% de bônus – assinantes do Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes do Clube Azul entre 1 a 2 anos (12 a 35 meses)',
            '+ 20% de bônus – assinantes do Clube Azul entre 3 e 4 anos (36 a 59 meses)',
            '+ 30% de bônus – assinantes do Clube Azul há mais de 5 anos (60 meses)'
        ]
    },
    {
        id: 45,
        source: 'Esfera',
        dest: 'Azul',
        bonus: 100,
        participants: ['Esfera'],
        startDate: '2025-11-18',
        endDate: '2025-11-19',
        rules: ['id: 45,',
            'Clientes Azul: 80% de bônus',
            'Assinantes Clube Azul: 100% de bônus',
            '+ 5% de bônus – assinantes do Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes do Clube Azul entre 1 a 2 anos (12 a 35 meses)',
            '+ 20% de bônus – assinantes do Clube Azul entre 3 e 4 anos (36 a 59 meses)',
            '+ 30% de bônus – assinantes do Clube Azul há mais de 5 anos (60 meses)'
        ]
    },
    {
        id: 46,
        source: 'C6 Bank',
        dest: 'Azul',
        bonus: 70,
        participants: ['C6 Bank'],
        startDate: '2025-12-11',
        endDate: '2025-12-14',
        rules: ['id: 46,',
            '40% de bônus – clientes Azul Fidelidade',
            '70% de bônus – assinantes Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul há mais de 6 meses',
            '+ 10% de bônus – assinantes do Clube Azul entre 1 a 2 anos (12 a 35 meses)',
            '+ 20% de bônus – assinantes do Clube Azul entre 3 e 4 anos (36 a 69 meses)',
            '+ 30% de bônus – assinantes do Clube Azul há mais de 5 anos (60 meses)'
        ]
    },
    {
        id: 47,
        source: 'Itaú',
        dest: 'Latam',
        bonus: 35,
        participants: ['Itaú'],
        startDate: '2025-01-10',
        endDate: '2025-01-10',
        rules: ['id: 47,',
            '20% de bônus – para todos os clientes LATAM Pass.',
            '35% de bônus – para clientes assinantes do Clube LATAM Pass.'
        ]
    },
    {
        id: 48,
        source: 'Caixa',
        dest: 'Latam',
        bonus: 164,
        participants: ['Caixa'],
        startDate: '2025-01-12',
        endDate: '2025-01-12',
        rules: ['id: 48,',
            '50% de bônus – para todos os clientes LATAM Pass.',
            '60% de bônus – para clientes categoria Gold e Gold Plus.',
            '80% de bônus – para clientes categoria Platinum.',
            '134% de bônus – para clientes categoria Black e Black Signature.',
            '+ 30% de bônus – para assinantes do Clube LATAM Pass.'
        ]
    },
    {
        id: 49,
        source: 'Esfera',
        dest: 'Latam',
        bonus: 30,
        participants: ['Esfera'],
        startDate: '2025-01-21',
        endDate: '2025-01-21',
        rules: ['id: 49,',
            '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para clientes assinantes do Clube LATAM Pass.'
        ]
    },
    {
        id: 50,
        source: 'Bancos',
        dest: 'Latam',
        bonus: 30,
        participants: [
            'Itaú',
            'Credicard',
            'Esfera',
            'CAIXA Econômica Federal',
            'Banco Banrisul',
            'Sisprime',
            'Unicred',
            'Banco Banestes',
            'Banco Pan',
            'Banco do Nordeste',
            'Banco Mercantil',
            'Bourbon Cartões',
            'Banpará',
            'Banco BV',
            'Banco Industrial BIB',
            'Banco BRB',
            'Sicredi',
            'C6 Bank'
        ],
        startDate: '2025-01-31',
        endDate: '2025-01-31',
        rules: ['id: 50,',
            '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para clientes assinantes do Clube LATAM Pass.'
        ]
    },
    {
        id: 52,
        source: 'Inter',
        dest: 'Azul',
        bonus: 80,
        participants: ['Inter'],
        startDate: '2025-01-24',
        endDate: '2025-01-24',
        rules: ['id: 52,', '60% de bônus – para todos os clientes Azul',
            '80% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).'
        ]
    },
    {
        id: 53,
        source: 'Esfera',
        dest: 'Azul',
        bonus: 60,
        participants: ['Esfera'],
        startDate: '2025-01-29',
        endDate: '2025-01-29',
        rules: ['id: 53,', '40% de bônus – para todos os clientes Azul.',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 54,
        source: 'C6 Bank',
        dest: 'Azul',
        bonus: 60,
        participants: ['C6 Bank'],
        startDate: '2025-01-31',
        endDate: '2025-01-31',
        rules: ['id: 54,', '40% de bônus – para todos os clientes Azul;',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 55,
        source: 'Livelo',
        dest: 'Azul',
        bonus: 70,
        participants: ['Livelo'],
        startDate: '2025-01-31',
        endDate: '2025-01-31',
        rules: ['id: 55,', '50% de bônus – para todos os clientes Azul;',
            '70% de bônus – para clientes assinantes do Clube Azul e/ou Clube Livelo.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 56,
        source: 'Caixa',
        dest: 'Smiles',
        bonus: 164,
        participants: ['Caixa'],
        startDate: '2025-01-12',
        endDate: '2025-01-12',
        rules: ['id: 56,', '80% de bônus – para todos os clientes Smiles',
            '130% de bônus – para assinantes do Clubes Smiles OU clientes Diamante.',
            '164% de bônus – para assinantes do Clubes Smiles E clientes Diamante.']
    },
    {
        id: 58,
        source: 'C6 Bank',
        dest: 'Latam',
        bonus: 30,
        participants: ['C6 Bank'],
        startDate: '2025-02-19',
        endDate: '2025-02-19',
        rules: ['id: 58,', '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 61,
        source: 'Itau',
        dest: 'Latam',
        bonus: 35,
        participants: ['Itau'],
        startDate: '2025-02-14',
        endDate: '2025-02-14',
        rules: ['id: 61,', '20% de bônus – para todos os clientes LATAM Pass.',
            '35% de bônus – para clientes assinantes do Clube LATAM Pass.']
    },
    {
        id: 59,
        source: 'Livelo',
        dest: 'Latam',
        bonus: 30,
        participants: ['Livelo'],
        startDate: '2025-02-24',
        endDate: '2025-02-24',
        rules: ['id: 59,', '30% de bônus – para clientes assinantes do Clube LATAM Pass e/ou Clube Livelo.']
    },
    {
        id: 60,
        source: 'Bancos',
        dest: 'Latam',
        bonus: 30,
        participants: ['Todos os bancos'],
        startDate: '2025-02-28',
        endDate: '2025-02-28',
        rules: ['id: 60,', '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para clientes assinantes do Clube LATAM Pass.']
    },
    {
        id: 62,
        source: 'Inter',
        dest: 'Azul',
        bonus: 60,
        participants: ['Inter'],
        startDate: '2025-02-07',
        endDate: '2025-02-07',
        rules: ['id: 62,', '40% de bônus – para todos os clientes Azul.',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 63,
        source: 'Esfera',
        dest: 'Azul',
        bonus: 60,
        participants: ['Esfera'],
        startDate: '2025-02-14',
        endDate: '2025-02-14',
        rules: ['id: 63,', '40% de bônus – para todos os clientes Azul.',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 64,
        source: 'Sicredi',
        dest: 'Azul',
        bonus: 70,
        participants: ['Sicredi'],
        startDate: '2025-02-02',
        endDate: '2025-02-05',
        rules: ['id: 64,', '50% de bônus – para todos os clientes Azul.',
            '70% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (de 6 a 11 meses).',
            '+ 10% de bônus – assinantes do Clube Azul (de 1 a 2 anos).',
            '+ 20% de bônus – assinantes do Clube Azul (de 3 a 4 anos).',
            '+ 30% de bônus – assinantes do Clube Azul  (de 5 anos ou mais).']
    },
    {
        id: 65,
        source: 'Itaú',
        dest: 'Azul',
        bonus: 60,
        participants: ['Itaú'],
        startDate: '2025-02-20',
        endDate: '2025-02-20',
        rules: ['id: 65,', '40% de bônus – para todos os clientes Azul;',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 66,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 60,
        participants: ['Todos os bancos'],
        startDate: '2025-02-21',
        endDate: '2025-02-21',
        rules: ['id: 66,', '40% de bônus – para todos os clientes Azul;',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 67,
        source: 'Banrisul',
        dest: 'Azul',
        bonus: 70,
        participants: ['Banrisul'],
        startDate: '2025-02-23',
        endDate: '2025-02-23',
        rules: ['id: 67,', '50% de bônus – para todos os clientes Azul;',
            '70% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 68,
        source: 'C6 Bank',
        dest: 'Azul',
        bonus: 60,
        participants: ['C6 Bank'],
        startDate: '2025-02-28',
        endDate: '2025-02-28',
        rules: ['id: 68,', '40% de bônus – para todos os clientes Azul;',
            '60% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 69,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-02-28',
        endDate: '2025-02-28',
        rules: ['id: 69,', '40% de bônus – para todos os clientes Azul;',
            '80% de bônus – para clientes assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses).',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses).',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 70,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-02-01',
        endDate: '2025-02-01',
        rules: ['id: 70,', 'Até 80% de bônus']
    },
    {
        id: 71,
        source: 'Sicredi',
        dest: 'Latam',
        bonus: 30,
        participants: ['Sicredi'],
        startDate: '2025-03-12',
        endDate: '2025-03-12',
        rules: ['id: 71,', '20% de bônus – para todos os clientes LATAM Pass;',
            '30% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 72,
        source: 'Itaú',
        dest: 'Latam',
        bonus: 30,
        participants: ['Itaú'],
        startDate: '2025-03-17',
        endDate: '2025-03-17',
        rules: ['id: 72,', '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para clientes assinantes do Clube LATAM Pass.']
    },
    {
        id: 73,
        source: 'Esfera',
        dest: 'Latam',
        bonus: 30,
        participants: ['Esfera'],
        startDate: '2025-03-21',
        endDate: '2025-03-21',
        rules: ['id: 73,', '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 74,
        source: 'Bancos',
        dest: 'Latam',
        bonus: 30,
        participants: ['Itaú', 'Credicard', 'Caixa Econômica Federal', 'Banco Banrisul', 'Sisprime', 'Unicred', 'Banco Banestes', 'Banco Pan', 'Banco do Nordeste', 'Banco Mercantil', 'Bourbon Cartões', 'Banpará', 'Banco BV', 'Banco Industrial BIB', 'Banco BRB', 'Sicredi', 'C6 Bank', 'Porto Seguro', 'Sicoob'],
        startDate: '2025-03-28',
        endDate: '2025-03-28',
        rules: ['id: 74,', '20% de bônus – para todos os clientes LATAM Pass.',
            '30% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 75,
        source: 'Itaú',
        dest: 'Azul',
        bonus: 70,
        participants: ['Itaú'],
        startDate: '2025-03-21',
        endDate: '2025-03-21',
        rules: ['id: 75,', '40% de bônus – transferindo até 20.000 pontos.',
            '50% de bônus – transferindo de 20.001 a 50.000 pontos.',
            '60% de bônus – transferindo a partir de 50.001 pontos.',
            '50% de bônus – transferindo até 20.000 pontos.',
            '60% de bônus – transferindo de 20.001 a 50.000 pontos.',
            '70% de bônus – transferindo a partir de 50.001 pontos.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses);',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses);',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 76,
        source: 'Inter',
        dest: 'Azul',
        bonus: 70,
        participants: ['Inter'],
        startDate: '2025-03-21',
        endDate: '2025-03-21',
        rules: ['id: 76,', '50% de bônus – para todos os clientes Azul.',
            '70% de bônus – para assinantes do Clube Azul.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses);',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses);',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 77,
        source: 'C6 Bank',
        dest: 'Azul',
        bonus: 70,
        participants: ['C6 Bank'],
        startDate: '2025-03-27',
        endDate: '2025-03-27',
        rules: ['id: 77,', '40% de bônus – transferindo até 20.000 pontos.',
            '50% de bônus – transferindo de 20.001 a 50.000 pontos.',
            '60% de bônus – transferindo a partir de 50.001 pontos.',
            '50% de bônus – transferindo até 20.000 pontos.',
            '60% de bônus – transferindo de 20.001 a 50.000 pontos.',
            '70% de bônus – transferindo a partir de 50.001 pontos.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses);',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses);',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 78,
        source: 'Livelo',
        dest: 'Azul',
        bonus: 90,
        participants: ['Livelo'],
        startDate: '2025-03-31',
        endDate: '2025-03-31',
        rules: ['id: 78,', '40% de bônus – para todos os clientes Azul;',
            '90% de bônus – para assinantes do Clube Azul e/ou Clube Livelo.',
            '+ 5% de bônus – assinantes do Clube Azul (há mais de 6 meses);',
            '+ 10% de bônus – assinantes do Clube Azul 1.000, 2.000, 3.000 ou 5.000 (há mais de 12 meses);',
            '+ 20% de bônus – assinantes do Clube Azul 10.000 ou 20.000 (há mais de 12 meses).']
    },
    {
        id: 79,
        source: 'Livelo',
        dest: 'Smiles',
        bonus: 90,
        participants: ['Livelo'],
        startDate: '2025-03-14',
        endDate: '2025-03-14',
        rules: ['id: 79,',
            '50% de bônus – para todos os clientes Smiles;',
            '80% de bônus – para assinantes do Clube Smiles OU clientes Diamante OU Clube Livelo;',
            '90% de bônus – para assinantes do Clube Smiles E Clube Livelo OU clientes Diamante E Clube Livelo.']
    },
    {
        id: 80,
        source: 'Inter',
        dest: 'Smiles',
        bonus: 90,
        participants: ['Inter'],
        startDate: '2025-03-18',
        endDate: '2025-03-18',
        rules: ['id: 80,', '50% de bônus – para todos os clientes Smiles;',
            '90% de bônus – para assinantes Clube Smiles e/ou cliente Diamante.']
    },
    {
        id: 81,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 100,
        participants: ['Todos os bancos'],
        startDate: '2025-03-18',
        endDate: '2025-03-18',
        rules: ['id: 81,', '100% de bônus – exclusiva para clientes categoria Diamante Magno.']
    },
    {
        id: 82,
        source: 'Itaú',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Itaú'],
        startDate: '2025-03-25',
        endDate: '2025-03-25',
        rules: ['id: 82,', '50% de bônus – para todos os clientes Smiles.',
            '80% de bônus – para assinantes do Clube Smiles ou clientes Diamante.']
    },
    {
        id: 83,
        source: 'Esfera',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Esfera'],
        startDate: '2025-03-26',
        endDate: '2025-03-26',
        rules: ['id: 83,', '50% de bônus – para todos os clientes Smiles.',
            '70% de bônus – para assinantes do Clube Smiles ou cliente Diamante OU Clube Esfera.',
            '80% de bônus – para assinantes do Clube Smiles ou cliente Diamante E Clube Esfera.']
    },
    {
        id: 84,
        source: 'Banestes',
        dest: 'Latam',
        bonus: 35,
        participants: ['Banestes'],
        startDate: '2025-04-17',
        endDate: '2025-04-17',
        rules: ['id: 84,', '20% de bônus – para todos os clientes LATAM Pass;', '35% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 85,
        source: 'BRB',
        dest: 'Latam',
        bonus: 35,
        participants: ['BRB'],
        startDate: '2025-04-17',
        endDate: '2025-04-17',
        rules: ['id: 85,', '20% de bônus – para todos os clientes LATAM Pass;', '35% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 86,
        source: 'Esfera',
        dest: 'Latam',
        bonus: 35,
        participants: ['Esfera'],
        startDate: '2025-04-23',
        endDate: '2025-04-23',
        rules: ['id: 86,', '20% de bônus – para todos os clientes LATAM Pass;', '35% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 87,
        source: 'Caixa',
        dest: 'Latam',
        bonus: 35,
        participants: ['Caixa'],
        startDate: '2025-04-30',
        endDate: '2025-04-30',
        rules: ['id: 87,', '20% de bônus – para todos os clientes LATAM Pass;', '35% de bônus – para assinantes do Clube LATAM Pass.']
    },
    {
        id: 88,
        source: 'Banestes',
        dest: 'Azul',
        bonus: 70,
        participants: ['Banestes'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 88,', 'Até 70% de bônus']
    },
    {
        id: 89,
        source: 'Inter',
        dest: 'Azul',
        bonus: 80,
        participants: ['Inter'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 89,', 'Até 80% de bônus']
    },
    {
        id: 90,
        source: 'Itaú',
        dest: 'Azul',
        bonus: 80,
        participants: ['Itaú'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 90,', 'Até 80% de bônus']
    },
    {
        id: 91,
        source: 'Esfera',
        dest: 'Azul',
        bonus: 60,
        participants: ['Esfera'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 91,', 'Até 60% de bônus']
    },
    {
        id: 92,
        source: 'Livelo',
        dest: 'Azul',
        bonus: 100,
        participants: ['Livelo'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 92,', 'Até 100% de bônus']
    },
    {
        id: 93,
        source: 'Bancos',
        dest: 'Azul',
        bonus: 70,
        participants: ['Todos os bancos'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 93,', 'Até 70% de bônus']
    },
    {
        id: 94,
        source: 'C6 Bank',
        dest: 'Azul',
        bonus: 80,
        participants: ['C6 Bank'],
        startDate: '2025-04-01',
        endDate: '2025-04-01',
        rules: ['id: 94,', 'Até 80% de bônus']
    },
    {
        id: 95,
        source: 'Banestes',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Banestes'],
        startDate: '2025-04-10',
        endDate: '2025-04-10',
        rules: ['id: 95,', '50% de bônus – para todos os clientes Smiles;',
            '80% de bônus – para assinantes do Clube Smiles e/ou clientes Diamante.']
    },
    {
        id: 96,
        source: 'BRB',
        dest: 'Smiles',
        bonus: 80,
        participants: ['BRB'],
        startDate: '2025-04-15',
        endDate: '2025-04-15',
        rules: ['id: 96,', '65% de bônus – para todos os clientes Smiles.',
            '80% de bônus – para assinantes do Clube Smiles e/ou clientes Diamante.']
    },
    {
        id: 97,
        source: 'Sicredi',
        dest: 'Smiles',
        bonus: 70,
        participants: ['Sicredi'],
        startDate: '2025-04-15',
        endDate: '2025-04-15',
        rules: ['id: 97,', '40% de bônus – para todos os clientes Smiles.',
            '70% de bônus – para assinantes do Clube Smiles e/ou clientes Diamante.']
    },
    {
        id: 98,
        source: 'Bancos',
        dest: 'Smiles',
        bonus: 80,
        participants: ['Todos os bancos'],
        startDate: '2025-04-17',
        endDate: '2025-04-17',
        rules: ['id: 98,', '70% de bônus – assinantes Clube Smiles Plano 1.000;',
            '73% de bônus – assinantes Clube Smiles Plano 2.000 e Plano 3.000;',
            '75% de bônus – assinantes Clube Smiles Plano 5.000;',
            '77% de bônus – assinantes Clube Smiles Plano 7.000;',
            '78% de bônus – assinantes Clube Smiles Plano Plano 10.000;',
            '80% de bônus – assinantes Clube Smiles Plano 20.000 e/ou Categoria Diamante.']
    }
];

export const anniversaries = [
    { program: 'Latam', month: 0, day: 15 }, // Janeiro
    { program: 'Smiles', month: 9, day: 22 },    // Outubro
    { program: 'Azul', month: 11, day: 15 },     // Dezembro
    { program: 'Livelo', month: 5, day: 10 },    // Junho
    { program: 'Esfera', month: 8, day: 5 },     // Setembro
    { program: 'Caixa', month: 0, day: 12 }      // Janeiro
];

export const programColors = {
    'Smiles': { primary: '#FF5A00', secondary: '#FFF0E6' },
    'Azul': { primary: '#003399', secondary: '#E6EEFF' },
    'Latam': { primary: '#FF0000', secondary: '#FFE6E6' },
    'Livelo': { primary: '#E6007E', secondary: '#FDE6F2' },
    'Esfera': { primary: '#000000', secondary: '#F2F2F2' },
    'Caixa': { primary: '#005CA9', secondary: '#E6F0F7' },
    'Itaú': { primary: '#EC7000', secondary: '#FDECE0' },
    'C6 Bank': { primary: '#212121', secondary: '#F2F2F2' },
    'Santander': { primary: '#EC0000', secondary: '#FDE6E6' },
    'Bradesco': { primary: '#CC092F', secondary: '#F9E6EA' }
};
